use-placeholderapi: true

# or "eng"
language: "ru"

#§§§§§§§
events:
  custom-join:
    toggle: true
    message: "§2[+] §f{player} присоединился к серверу"
  custom-quit:
    toggle: true
    message: "§c[-] §f{player} покинул сервер"
  custom-death:
    toggle: true
    message: "§8{death_message}"

#Available placeholders for usage:
#"{world-color}"
#{world-prefix}"
#"{prefix}"
#{placeholder-prefix}"
#name-color}"
#{message-color}"
#{player}"
#{receiver-prefix}"
#{receiver-color}"
#{receiver}"
#{sender}"
#{message}"
#You can change their order anyway you want, write them in msgformat or delete, and write them into each other as shown in:
#prefix: "§7[§7{group} &#00ffccGROUP§7]"
#Here {group} is used in {prefix}
chat:
  global:
    toggle: true
    prefix: "[G]"
    name-color: "§f"
    message-color: "§f"
    placeholder-prefix: "%luckperms_prefix%" #Можно оставить пустым/You can leave it clear
    placeholder-suffix: "%luckperms_suffix%"
    world-prefix:
      enabled: true
      format: "§8[{world}] "  # world — будет заменён на имя мира/will be replaced with name of the world
    msgformat: "{world-color}{prefix} §r{placeholder-prefix}{name-color}{player} §7>> {message-color}{message}"

  local:
    toggle: true
    radius: 50
    prefix: "[L]"
    name-color: "§f"
    message-color: "§7"
    placeholder-prefix: "%luckperms_prefix%"
    world-prefix:
      enabled: true
      format: "§8[{world}] "
    msgformat: "§7{prefix} §r{placeholder-prefix}{name-color}{player} §7>> {message-color}{message}"

  admin:
    toggle: true
    prefix: "[A-Chat]"
    name-color: "§f"
    message-color: "§f"
    placeholder-prefix: "%luckperms_prefix%"
    world-prefix:
      enabled: false
      format: "§8[{world}] "
    msgformat: "§d{prefix} §r{placeholder-prefix}{name-color}{player} §7>> {message-color}{message}"

  appeal:
    toggle: true
    prefix: "[&#f75eabAPPEAL§8]"
    name-color: "§f"
    message-color: "§f"
    placeholder-prefix: "%luckperms_prefix%"
    world-prefix:
      enabled: false
      format: "§8[{world}] "
    msgformat: "§8{prefix} §r{placeholder-prefix}{name-color}{player} §7>> {message-color}{message}"

  spy:
    toggle: true  
    prefix: "[SPY] [✉]"
    name-color: "§b"
    message-color: "§7"
    receiver-prefix: ""
    receiver-color: "§e"
    placeholder-prefix: "%luckperms_prefix%"
    world-prefix:
      enabled: true
      format: "§8[{world}] "
    msgformat: "§1{prefix} §r{placeholder-prefix}{name-color}{player} §b→ §r{receiver-prefix}{receiver-color}{receiver} §b>> {message-color}{message}"

  private:
    toggle: true
    prefix: "[✉]"
    name-color: "&#7cdaf7"
    receiver-prefix: "%luckperms_prefix%"
    receiver-color: "&#f2e77e"
    message-color: "§f"
    placeholder-prefix: "%luckperms_prefix%"
    world-prefix:
      enabled: false
      format: "§8[{world}] "
    msgformat: "§3{prefix} §r{placeholder-prefix}{name-color}{sender} §b→ §r{receiver-prefix}{receiver-color}{receiver} §b>> {message-color}{message}"